<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>VoicePlayer</AssemblyName>
    <RootNamespace>VoicePlayer</RootNamespace>
    <InvariantGlobalization>false</InvariantGlobalization>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="app.ico" />
    <Resource Include="logo.png" />
  </ItemGroup>
</Project>
